#!/bin/bash
setEnv(){
cd $1
    if [ ! -f ".env" ]; then
        echo "no .env"
        exit
    fi
    for line in $(cat .env)
    do
        export ${line}
    done
    cd ../
}
type=$1
if [[ ${type} = "admin" ]]
then
 setEnv admin
 gin --port 8888  --appPort 8880 --build ./admin
else
 setEnv web
 gin --port 9999  --appPort 9990 --build ./web 
fi

